---
title: "Final_Tree"
author: "AmyLiu"
date: "2023-03-12"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Use the standardized training data to train tree-based models. Bagging with 100 trees and m = 57 results in testing MSE of 0.043, random forest with m=8 and 100 trees restuls in testing MSE of 0.036. **

```{r}
# read in data
library(randomForest)
train = read.csv("train_stand.csv")
train <- subset(train, select = -c(X))
test = read.csv("test_stand.csv")
test <- subset(test, select = -c(X))
true = test$classes
```

```{r}
# Bagging (Random forests with m=p) and 100 trees
bag.model = randomForest(classes~., data=train,
                           mtry=(ncol(train)-1),importance=TRUE, ntree=100)
summary(bag.model)
```

```{r}
# Prediction on training set for bagging
training_res = predict(bag.model, train)
cat("Training MSE: ", mean((training_res-train$classes)^2))
```


```{r}
# Prediction on test set for bagging
bag.predicted = predict(bag.model, test)

# Plot prediction performance
plot(bag.predicted, true)
abline (0,1)

# MSE on test set
mean((bag.predicted-true)^2)
```

```{r}
# Random forests with m=sqrt(p) and 100 trees. p=57, let m be 8
RF.model = randomForest(classes~., data=train,
                           mtry=8,importance=TRUE, ntree=100)
summary(RF.model)
```

```{r}
# Prediction on test set
RF.predicted = predict(RF.model, test)

# Plot prediction performance
plot(RF.predicted, true)
abline(0,1)

# MSE on test set
mean((RF.predicted -true)^2)
```